[workspace]
members = [
    "fastjob",
    "fastjob-client",
    "fastjob-admin",
    "components/alarm",
    "components/app",
    "components/app/core",
    "components/app/scheduler",
    "components/app/worker",
    "components/error",
    "components/error",
    "components/metrics",
    "components/tracing",
    "components/utils",
    "components/resouce-constraints",
    "components/stack",
    "components/timeout",
    "components/retry",
    "components/transport",
    "components/rocks"
]

[profile.dev]
debug = false
[profile.test]
debug = false