[workspace]
members = [
    "fastjob",
    "fastjob-admin",
    "components/app",
    "components/error",
    "components/error",
    "components/metrics",
    "components/tracing",
    "components/utils",
]


[profile.dev]
debug = false
[profile.test]
debug = false